apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::873775474693:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-Q1CQ9W290G74
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::873775474693:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-31T21:50:33Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-03-31T21:50:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1455"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 9601eb3f-7cd7-40d7-9627-94abda7d2d66
