apiVersion: v1
data:
  mapRoles: |
   - groups:
      - system:masters
      rolearn: arn:aws:iam::873775474693:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::873775474693:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-XF94F1ERHUHH
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-31T00:23:44Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-03-31T00:23:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1801"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ce5e19ac-76af-43c9-bd25-e69b56bf70f2
